# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 12:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultantform', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidiary',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Client'),
        ),
        migrations.AddField(
            model_name='strategyp',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Client'),
        ),
        migrations.AddField(
            model_name='strategyp',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Project'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Client'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Project'),
        ),
        migrations.AddField(
            model_name='scriptp',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Client'),
        ),
        migrations.AddField(
            model_name='scriptp',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Project'),
        ),
        migrations.AddField(
            model_name='script',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Client'),
        ),
        migrations.AddField(
            model_name='script',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Project'),
        ),
        migrations.AddField(
            model_name='relatedcompany',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Client'),
        ),
        migrations.AddField(
            model_name='problemsolvingp',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Client'),
        ),
        migrations.AddField(
            model_name='problemsolvingp',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Project'),
        ),
        migrations.AddField(
            model_name='problemsolving',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Client'),
        ),
        migrations.AddField(
            model_name='problemsolving',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Project'),
        ),
        migrations.AddField(
            model_name='miomp',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Client'),
        ),
        migrations.AddField(
            model_name='miomp',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Project'),
        ),
        migrations.AddField(
            model_name='miom',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Client'),
        ),
        migrations.AddField(
            model_name='miom',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Project'),
        ),
        migrations.AddField(
            model_name='duediligencep',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Client'),
        ),
        migrations.AddField(
            model_name='duediligencep',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Project'),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Client'),
        ),
        migrations.AddField(
            model_name='duediligence',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Project'),
        ),
        migrations.AddField(
            model_name='digitalizationp',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Client'),
        ),
        migrations.AddField(
            model_name='digitalizationp',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Project'),
        ),
        migrations.AddField(
            model_name='digitalization',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Client'),
        ),
        migrations.AddField(
            model_name='digitalization',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Project'),
        ),
        migrations.AddField(
            model_name='branch',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Client'),
        ),
        migrations.AddField(
            model_name='backgroundcheckb',
            name='c1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ca', to=settings.AUTH_USER_MODEL, verbose_name='Currently With'),
        ),
        migrations.AddField(
            model_name='backgroundcheckb',
            name='c10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cj', to=settings.AUTH_USER_MODEL, verbose_name='Currently With'),
        ),
        migrations.AddField(
            model_name='backgroundcheckb',
            name='c11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ck1', to=settings.AUTH_USER_MODEL, verbose_name='Currently With'),
        ),
        migrations.AddField(
            model_name='backgroundcheckb',
            name='c12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cl2', to=settings.AUTH_USER_MODEL, verbose_name='Currently With'),
        ),
        migrations.AddField(
            model_name='backgroundcheckb',
            name='c13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cm3', to=settings.AUTH_USER_MODEL, verbose_name='Currently With'),
        ),
        migrations.AddField(
            model_name='backgroundcheckb',
            name='c2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cb', to=settings.AUTH_USER_MODEL, verbose_name='Currently With'),
        ),
        migrations.AddField(
            model_name='backgroundcheckb',
            name='c3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cc', to=settings.AUTH_USER_MODEL, verbose_name='Currently With'),
        ),
        migrations.AddField(
            model_name='backgroundcheckb',
            name='c4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cd', to=settings.AUTH_USER_MODEL, verbose_name='Currently With'),
        ),
        migrations.AddField(
            model_name='backgroundcheckb',
            name='c5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ce', to=settings.AUTH_USER_MODEL, verbose_name='Currently With'),
        ),
        migrations.AddField(
            model_name='backgroundcheckb',
            name='c6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cf', to=settings.AUTH_USER_MODEL, verbose_name='Currently With'),
        ),
        migrations.AddField(
            model_name='backgroundcheckb',
            name='c7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cg', to=settings.AUTH_USER_MODEL, verbose_name='Currently With'),
        ),
        migrations.AddField(
            model_name='backgroundcheckb',
            name='c8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ch', to=settings.AUTH_USER_MODEL, verbose_name='Currently With'),
        ),
        migrations.AddField(
            model_name='backgroundcheckb',
            name='c9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ci', to=settings.AUTH_USER_MODEL, verbose_name='Currently With'),
        ),
        migrations.AddField(
            model_name='backgroundcheckb',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Client'),
        ),
        migrations.AddField(
            model_name='backgroundcheck',
            name='c1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c1', to=settings.AUTH_USER_MODEL, verbose_name='Currently With'),
        ),
        migrations.AddField(
            model_name='backgroundcheck',
            name='c10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c10', to=settings.AUTH_USER_MODEL, verbose_name='Currently With'),
        ),
        migrations.AddField(
            model_name='backgroundcheck',
            name='c11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c11', to=settings.AUTH_USER_MODEL, verbose_name='Currently With'),
        ),
        migrations.AddField(
            model_name='backgroundcheck',
            name='c12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c12', to=settings.AUTH_USER_MODEL, verbose_name='Currently With'),
        ),
        migrations.AddField(
            model_name='backgroundcheck',
            name='c13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c13', to=settings.AUTH_USER_MODEL, verbose_name='Currently With'),
        ),
        migrations.AddField(
            model_name='backgroundcheck',
            name='c2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c2', to=settings.AUTH_USER_MODEL, verbose_name='Currently With'),
        ),
        migrations.AddField(
            model_name='backgroundcheck',
            name='c3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c3', to=settings.AUTH_USER_MODEL, verbose_name='Currently With'),
        ),
        migrations.AddField(
            model_name='backgroundcheck',
            name='c4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c4', to=settings.AUTH_USER_MODEL, verbose_name='Currently With'),
        ),
        migrations.AddField(
            model_name='backgroundcheck',
            name='c5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c5', to=settings.AUTH_USER_MODEL, verbose_name='Currently With'),
        ),
        migrations.AddField(
            model_name='backgroundcheck',
            name='c6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c6', to=settings.AUTH_USER_MODEL, verbose_name='Currently With'),
        ),
        migrations.AddField(
            model_name='backgroundcheck',
            name='c7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c7', to=settings.AUTH_USER_MODEL, verbose_name='Currently With'),
        ),
        migrations.AddField(
            model_name='backgroundcheck',
            name='c8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c8', to=settings.AUTH_USER_MODEL, verbose_name='Currently With'),
        ),
        migrations.AddField(
            model_name='backgroundcheck',
            name='c9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c9', to=settings.AUTH_USER_MODEL, verbose_name='Currently With'),
        ),
        migrations.AddField(
            model_name='backgroundcheck',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Client'),
        ),
        migrations.AddField(
            model_name='article',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Client'),
        ),
        migrations.AddField(
            model_name='article',
            name='services_opted',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.Product'),
        ),
    ]
