# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 12:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultantform', '0002_auto_20170915_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundcheckb',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 15, 18, 3, 4, 971672)),
        ),
    ]
