# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 12:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultantform', '0003_auto_20170915_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='type_of_business',
        ),
        migrations.AddField(
            model_name='article',
            name='type_of_activity',
            field=models.CharField(blank=True, choices=[('manufacturing', 'Manufacturing'), ('services', 'Services'), ('retail', 'Retail'), ('distribution', 'Distribution'), ('job works oem', 'Job works oem'), ('r and d', 'R and D')], max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='type_of_company',
            field=models.CharField(blank=True, choices=[('proprietary', 'Proprietary'), ('partnership', 'Partnership'), ('llp', 'LLP'), ('private_ltd', 'Private Ltd'), ('limited', 'Limited'), ('privately_held', 'Private held'), ('publically_traded', 'Publically traded')], max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='services_opted',
            field=models.ManyToManyField(blank=True, to='myapp.Product'),
        ),
        migrations.AlterField(
            model_name='backgroundcheckb',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 27, 18, 14, 32, 871363)),
        ),
    ]
