# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 05:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultantform', '0004_auto_20170927_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type_of_industry',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='backgroundcheckb',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 28, 10, 58, 13, 901583)),
        ),
    ]
